<?php

declare(strict_types=1);

namespace Laith98Dev\palethia\network\raknet\protocol;

enum RakPacketId: int
{
	case INVALID = -1;
	case CONNECTED_PING = 0x00;
	case UNCONNECTED_PING = 0x01;
	case UNCONNECTED_PING_OPEN_CONNECTIONS = 0x02;
	case CONNECTED_PONG = 0x03;
	case OPEN_CONNECTION_REQUEST_ONE = 0x05;
	case OPEN_CONNECTION_REPLY_ONE = 0x06;
	case OPEN_CONNECTION_REQUEST_TWO = 0x07;
	case OPEN_CONNECTION_REPLY_TWO = 0x08;
	case CONNECTION_REQUEST = 0x09;
	case CONNECTION_REQUEST_ACCEPTED = 0x10;
	case CONNECTION_ATTEMPT_FAILED = 0x11;
	case ALREADY_CONNECTED = 0x12;
	case NEW_INCOMING_CONNECTION = 0x13;
	case DISCONNECTION_NOTIFICATION = 0x15;
	case CONNECTION_LOST = 0x16;
	case INCOMPATIBLE_PROTOCOL_VERSION = 0x19;
	case UNCONNECTED_PONG = 0x1c;
	case USER_PACKET_ENUM = 0x86;
}
